export const carrouselData = [
    {
        image: "https://i2.wp.com/confirmado.net/wp-content/uploads/2020/10/terremoto_turquia.jpg",
        title:"Terremoto en Turquía",
        description:'En la ciudad turca de Malatya, gravemente dañada por el gran terremoto del pasado febrero, nueve edificios de quince plantas fueron demolidos simultáneamente con explosivos. En la operación fueron utilizados más de 1.660 kilos de dinamita, lo que estableció un récord de la explosión más grande del mundo. A pesar de que nubes de polvo cubrieron la zona aledaña tras el derrumbe, las autoridades señalaron que la demolición de los bloques se había completado sin problemas. En la ciudad turca de Malatya, gravemente dañada por el gran terremoto del pasado febrero, nueve edificios de quince plantas fueron demolidos simultáneamente con explosivos. En la operación fueron utilizados más de 1.660 kilos de dinamita, lo que estableció un récord de la explosión más grande del mundo. A pesar de que nubes de polvo cubrieron la zona aledaña tras el derrumbe, las autoridades señalaron que la demolición de los bloques se había completado sin problemas. En la ciudad turca de Malatya, gravemente dañada por el gran terremoto del pasado febrero, nueve edificios de quince plantas fueron demolidos simultáneamente con explosivos. En la operación fueron utilizados más de 1.660 kilos de dinamita, lo que estableció un récord de la explosión más grande del mundo. A pesar de que nubes de polvo cubrieron la zona aledaña tras el derrumbe, las autoridades señalaron que la demolición de los bloques se había completado sin problemas.'
    },{
        image: "https://www.semana.com/resizer/Ek2dRExNYgPGlXJooigqK1U6W0o=/1280x720/smart/filters:format(jpg):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/semana/MRMVROW7C5FKZN4WMDTDLVXDPU.jpg",
        title:"Terremoto en Turquía 2",
        description:"Frank Hoogerbeets analizó esta semana un gráfico de fluctuaciones en las que sugiere que España y Portugal también corren el peligro de sufrir un temblor de tierra, y pidió a estos dos países mantnerse en alerta por dicha amenaza. Este científico ya había alertado sobre posibles movimientos telúricos en la región, tras el mortal sismo de Marruecos el pasado 8 de septiembre. Mostró un gráfico y una imagen del planeta tierra en la que puso en color morado el sur de España y el norte de Marruecos, que representaban zonas de actividad sísmica fuerte. Frank Hoogerbeets analizó esta semana un gráfico de fluctuaciones en las que sugiere que España y Portugal también corren el peligro de sufrir un temblor de tierra, y pidió a estos dos países mantnerse en alerta por dicha amenaza. Este científico ya había alertado sobre posibles movimientos telúricos en la región, tras el mortal sismo de Marruecos el pasado 8 de septiembre. Mostró un gráfico y una imagen del planeta tierra en la que puso en color morado el sur de España y el norte de Marruecos, que representaban zonas de actividad sísmica fuerte."
    },{
        image: "https://www.eleconomista.com.mx/__export/1676509440126/sites/eleconomista/img/2023/02/13/terremoto_turquia.jpg_554688468.jpg",
        title:"Terremoto en Turquía 3",
        description:'Pero ahora, Özlem, más de medio año después, sigue acumulando más dosis de buena suerte. Su edificio aguantó, está entero. Fue catalogado como seguro. Özlem y su familia viven bajo su propio techo. Cientos de miles de sus vecinos de la ciudad de Antakya, en la región de Hatay —la más afectada por el seísmo— no pueden decir lo mismo. Pero ahora, Özlem, más de medio año después, sigue acumulando más dosis de buena suerte. Su edificio aguantó, está entero. Fue catalogado como seguro. Özlem y su familia viven bajo su propio techo. Cientos de miles de sus vecinos de la ciudad de Antakya, en la región de Hatay —la más afectada por el seísmo— no pueden decir lo mismo. Frank Hoogerbeets analizó esta semana un gráfico de fluctuaciones en las que sugiere que España y Portugal también corren el peligro de sufrir un temblor de tierra, y pidió a estos dos países mantnerse en alerta por dicha amenaza. Este científico ya había alertado sobre posibles movimientos telúricos en la región, tras el mortal sismo de Marruecos el pasado 8 de septiembre. Mostró un gráfico y una imagen del planeta tierra en la que puso en color morado el sur de España y el norte de Marruecos, que representaban zonas de actividad sísmica fuerte.'
    }
]